version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bus_booking_api
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - network

    nginx:
        image: nginx:stable-alpine
        container_name: nginx_server
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - network

    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    mysql_data:
